# These are supported funding model platforms

ko_fi: omegajoctan

custom: ['https://www.mql5.com/en/market/product/94160','https://www.mql5.com/en/market/product/99014','https://www.mql5.com/en/market/product/96490']
